### ISSUE TITLE
Drivers causes micro stutter.

### ISSUE THREAD

**Issue by chadstewart** [dantarion/SF5DInput#11]
Just noticed this today but the drivers causes the game to micro stutter every second or so. Definitely a fixed value. Just tested it, once it's uninstalled the stutter goes away. The stutter may also eat inputs but that is currently only speculation.

**Comment by michaelmarcuccio** [comment]
The build I have absolutely does not have micro stutter. On windows 10 with gtx 1080 and 120hz monitor. It could be an older version of the driver maybe?

**Comment by chadstewart** [comment]
Could be. I was using 0.0.2 build and it was for sure causing it on my machine. Guess I should include my PC specs.

PC:
Intel i7-4770k
Memory: 16GB
GPU: Nvidia GTX 980
OS: Windows 10

I tried using the newest build but the error I got was that memory at some location referenced memory at another location and it couldn't be read. Either way, I haven't had problems since removing the dlls. May just be my machine but it's something worth inspecting.

**Comment by michaelmarcuccio** [comment]
Use this build [ https://petitl.fr/dl/sf5dinput-snapshot-issue8-fix.zip](https://petitl.fr/dl/sf5dinput-snapshot-issue8-fix.zip) It was made for one of the other issues threads and it solved all the problems. Use only this .dll and not the other ones from the build you were using(it came with 2, now just use this 1).

**Comment by chadstewart** [comment]
Ahh okay okay. I tried using it and it doesn't cause the same stutter that it did before. Thank you. I'll close the issue.
