### ISSUE TITLE
Improvement request: Beep when using hotkey for switching sides

### ISSUE THREAD

**Issue by pokeshark** [dantarion/SF5DInput#13]
Hi Dantarion and WydD,

Great project, helps with hosting offlines on PC a lot, even for other games as well like Rocket League. So, thanks!

One small suggestion, if you will: when using the hotkey for switching player sides, can you play a sound to know it registered? The windows beep sound will suffice: System.Media.SystemSounds.Beep.Play();

PS: I would commit the change myself, but I don't have enough SSD space to install Visual Studio and test the change

**Comment by WydD** [comment]
Glad to know it works right of the bat for other games :)
I'll test this at some points to see how it works. thanks for the idea of using systemsounds.

**Comment by dantarion** [comment]
https://msdn.microsoft.com/en-us/library/ms679277(VS.85).aspx
This should work nicely.

**Comment by WydD** [comment]
Played with it a bit.
Beep works but it's aggressive and ignores the application sound level (resulting in a violent beep noise for me :p).
I used PlaySound to play a default windows sound (here "Media\Windows Hardware Insert.wav"), available in win7-8-10 and it is considered in the sound channel of SFV.

@pokeshark Let me know if this works for you https://petitl.fr/dl/sf5dinput-snapshot-sound-notify.zip

**Comment by pokeshark** [comment]
@WydD it works, tested in Windows7 with 3 different controllers (PS360+, DS3, some DS3 knock-off). thanks!
