### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by Kenzeira** [dantarion/SF5DInput#14]
Want just thank you so much. Working like a charm in my Madcatz TE (1) Soul Calibur V Edition. Happy now i don't need use third party software like JoyToKey or x360ce for my stick.
Don't work in my PS3 controller with MotionInJoy 0.7.1001 in the default DInput mode, but that's ok cause works when enable the XInput one.

![6335963837_6ae2edb182](https://cloud.githubusercontent.com/assets/21092575/17758410/81c442f6-64c5-11e6-9b48-e76171a8f251.jpg)

**Comment by dantarion** [comment]
yw
