### ISSUE TITLE
Support for 'Generic USB Joystick'

### ISSUE THREAD

**Issue by fp12** [dantarion/SF5DInput#18]
Hey,
I'm trying to make my 'Generic USB Joystick' (https://www.focusattack.com/ps3-pc-zero-delay-usb-encoder-pcb-american-style-controls/) work with your dll, but with no luck yet (for reference, it works with x360ce).
Could you point me on what can go wrong and I'll try to debug it?
Many thanks!

**Comment by fp12** [comment]
Update: I can make it 'work' since for this device, instance->wUsage == 4 (not 5).
That said, even with that, only the buttons are working...
On the FocusAttack page, it is said: 

> Street Fighter V offers "legacy control" for PS3 joysticks via day-one update.  Please be sure to check whether "mode" on your Zero Delay PCBA is set to "joystick" rather than left analog, or joystick control will not function.

Edit: using x360ce, I confirmed that the default directions are mapped to left joystick. So, once I can plug a button for this 'mode' behaviour, I'll be able to confirm if the directions work with the d-pad mode.

**Comment by dantarion** [comment]
the legacy support text you quoted has to do with PS4 SFV, not PC. PC SFV does not natively support PS4 controllers. SF5Input requires D-pad input for now but that may change in a future version

**Comment by fp12** [comment]
Yes, indeed. It was more to point out that the default directions are mapped to left stick but can be changed to d-pad easily.
Anyway, I could finally test it and it's working.
I'll submit a PR for this issue! Let me know!

**Comment by dantarion** [comment]
@WydD added analog support to master branch!
