### ISSUE TITLE
Frame drops issues, sometimes massive

### ISSUE THREAD

**Issue by WydD** [dantarion/SF5DInput#4]
Reported on reddit by some users, for instance https://www.reddit.com/r/StreetFighter/comments/4oqpap/dantarions_dinput_plugin_for_sfv_alpha_002_feat/d4erz5u

Venom sticks seem to be massive frame droppers. Sometimes people notice 1-2 frame drops, I dont know if we can avoid them.

**Comment by WydD** [comment]
Proposed fix: launch a thread to detect the devices, unfortunately this will lead to sensitive devs and we have to be careful.

Also we have to steal some of the code from x360ce like https://github.com/x360ce/x360ce/blob/65106bc9e39f37a958be45acbfe53a97dc097038/x360ce/x360ce/Controller.cpp#L575 which may prevent other drops which already existed in 0.0.1. Also the cooperative level should be better handled to avoid faulty devices.

**Comment by WydD** [comment]
This has been fixed in the PR https://github.com/dantarion/SF5DInput/pull/7
The user tested the snapshot build and everything seems fine https://www.reddit.com/r/StreetFighter/comments/4oqpap/dantarions_dinput_plugin_for_sfv_alpha_002_feat/d4v5wum?context=3

**Comment by WydD** [comment]
Also confirmed by reddit user /u/UltimaBlankk who had the same problems.

**Comment by dantarion** [comment]
Ill make a release of this sometime this week, thanks!
