### ISSUE TITLE
Make controller switching more explicit

### ISSUE THREAD

**Issue by WydD** [dantarion/SF5DInput#8]
EDIT: originally I thought it was a weird bug but its only key bindings for controller switch that are too sensitive making the user completely in the dark about what happens.

Mentionned by @sesq92 here https://github.com/dantarion/SF5DInput/issues/5#issuecomment-234755778

I think it's an issue when DirectX fails to read the device for any reason (hardware default or pilot busy or anything else). x360ce ignores this (more exactly it considers the device unplugged but reacquire it on the next frame) and we interpret this as unplugged and we remove it from the device list. This is not the right behaviour as the detection of unplugs must come from the device enumeration.

For the record, what model is your arcade stick @sesq92 ?

I'll fix this in the afternoon.

**Comment by WydD** [comment]
I prepared a fix, device removal is no longer dependant on reading failures.
Personally I never experienced this (PS360+) even on very long sessions so I cant reproduce.

I know it can be a pain to test this out but could you try this build? I'm fairly confident the issue is fixed but in case I'm wrong I'm sorry if you fail a match because of this https://petitl.fr/dl/sf5dinput-snapshot-issue8-fix.zip

**Comment by michaelmarcuccio** [comment]
I am using a Madcatz TE2, the blue one. It failed once for me on ps3 mode and once on ps4 mode. I also have a Hori RAP4 plugged in next to it for player 2 but it was inactive for my sessions yesterday. I would love to try out the build. I'll let you know if there are any problems later tonight. Thanks again!

**Comment by michaelmarcuccio** [comment]
Same issue happened again. I have more information this time, though. My player 1 stick disables itself all the sudden, then the player 2 stick that I have plugged in for no reason (the hori rap4), becomes player 1 stick and it's now the only stick that works until I restart the game. The issue isn't in the stick because I check joy.cpl and the stick functions fine there after the game stops working for it. Let me know if you have any ideas or suggestions. 

Edit: also this may help with troubleshooting. It happens when the match loads, as in going to round 2, FIGHT and then stick disables. It has not once disabled in menus or pre-matches or anything

**Comment by WydD** [comment]
Are you sure you have not pressed Home + Right or Select + Start + Right during match loads? If so, this binds you to player2 with your madcatz and the player1 becomes the hrap.

**Comment by michaelmarcuccio** [comment]
Yea, absolutely sure no inputs were done on the second stick(hori rap4). it is sitting on a desk with nothing around it. Maybe its sending an input software wise? 
Edit: nor those inputs on p1 stick I'm pretty sure

**Comment by WydD** [comment]
No I was talking about the input you can input on the first stick.

**Comment by michaelmarcuccio** [comment]
I just had it sitting in my lap, I probably pressed some punch and kicks but never the home button or select button. I hope it wasn't just my fault, that would be kinda silly. I'm going to test it real quick.

**Comment by michaelmarcuccio** [comment]
Update: You are definitely right, I just tested it out and Start+Select+ Right is most likely the culprit. I will test this same version again and make sure not to mash any of that lol. Sorry about that.

Yea I like to plink start and select rapidly while spinning the stick around haha.

**Comment by WydD** [comment]
Yeah I'm not quite satisfied with this solution I'll think of a better way of doing this (like you have to press for 3s or something like that)

**Comment by WydD** [comment]
To avoid problems, here's a build that does not allow any switching https://petitl.fr/dl/sf5dinput-snapshot-no-switch.zip
If you want to play your HRAP as player 1, you need to disconnect both sticks and plug hrap then the TE2 while the game is running.
Let me know :)

**Comment by michaelmarcuccio** [comment]
Was there ever a release with all of these features?
